# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_geohashrs_wrappers", use_symbols = TRUE, package_name = "geohashrs")

#' @usage NULL
#' @useDynLib geohashrs, .registration = TRUE
NULL

#' Print coordinate
#' @export
gh_encode <- function(x, y, length) .Call(wrap__gh_encode, x, y, length)

#' Find neighbor of a geohash in the requested direction
#' @export
gh_neighbor <- function(geohash, direction) .Call(wrap__gh_neighbor, geohash, direction)

#' Decode a geohash
gh_decode <- function(geohash) .Call(wrap__gh_decode, geohash)


# nolint end
